sudo: false

language: php

matrix:
  fast_finish: true
  include:

    - php: 5.2
      env: PHPCS_VERSION="1.5.6"
    - php: 5.2
      env: PHPCS_VERSION="master"

    - php: 5.3
      env: COVERALLS_VERSION="~1.0" PHPCS_VERSION=">=1.5.1,<2.0"
    - php: 5.3
      env: COVERALLS_VERSION="~1.0" PHPCS_VERSION=">=2.0"

    - php: 5.4
      env: COVERALLS_VERSION="~1.0" PHPCS_VERSION=">=1.5.1,<2.0"
    - php: 5.4
      env: COVERALLS_VERSION="~1.0" PHPCS_VERSION=">=2.0"

    - php: 5.5
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION=">=1.5.1,<2.0"
    - php: 5.5
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION=">=2.0"
    - php: 5.5
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION="dev-master"

    - php: 5.6
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION=">=1.5.1,<2.0"
    - php: 5.6
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION=">=2.0"
    - php: 5.6
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION="dev-master"

    - php: 7.0
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION=">=1.5.1,<2.0"
    - php: 7.0
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION=">=2.0"
    - php: 7.0
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION="dev-master" SNIFF=1

    - php: 7.1
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION=">=1.5.1,<2.0"
    - php: 7.1
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION=">=2.0"
    - php: 7.1
      env: COVERALLS_VERSION="dev-master" PHPCS_VERSION="dev-master"


before_install:
  # PHP 5.3+: set up test environment using Composer.
  - if [[ $TRAVIS_PHP_VERSION > "5.2" ]]; then composer self-update; fi
  - if [[ $TRAVIS_PHP_VERSION > "5.2" ]]; then composer require --dev satooshi/php-coveralls:${COVERALLS_VERSION}; fi
  - if [[ $TRAVIS_PHP_VERSION > "5.2" ]]; then composer require squizlabs/php_codesniffer:${PHPCS_VERSION}; fi
  - if [[ $TRAVIS_PHP_VERSION > "5.2" ]]; then composer install; fi
  # PHP 5.2: set up test environment using git cloning.
  - if [[ $TRAVIS_PHP_VERSION < "5.3" ]]; then export PHPCS_DIR=/tmp/phpcs; fi
  - if [[ $TRAVIS_PHP_VERSION < "5.3" ]]; then export PHPCS_BIN=$PHPCS_DIR/scripts/phpcs; fi
  - if [[ $TRAVIS_PHP_VERSION < "5.3" ]]; then mkdir -p $PHPCS_DIR && git clone --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git -b $PHPCS_VERSION $PHPCS_DIR; fi
  - if [[ $TRAVIS_PHP_VERSION < "5.3" ]]; then $PHPCS_BIN --config-set installed_paths $(pwd); fi

before_script:
  - if [[ $TRAVIS_PHP_VERSION > "5.2" ]]; then mkdir -p build/logs; fi
  - phpenv rehash

script:
  - if [[ $TRAVIS_PHP_VERSION > "5.2" ]]; then ln -s `pwd` vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility; fi
  - find -L . -path ./Tests/sniff-examples -prune -o -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs . --standard=./phpcs.xml; fi
  - phpunit --configuration phpunit-travis.xml --coverage-clover build/logs/clover.xml

after_success:
  - if [[ $TRAVIS_PHP_VERSION > "5.2" ]]; then php vendor/bin/coveralls -v -x build/logs/clover.xml; fi
