name: Codechecker CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          # Highest php versions supported by each branch (with main always being tested twice).
          - php: 8.3
            moodle-branch: main
            database: pgsql
          - php: 8.3
            moodle-branch: main
            database: mariadb
          - php: 8.3
            moodle-branch: MOODLE_500_STABLE
            database: pgsql
          - php: 8.3
            moodle-branch: MOODLE_405_STABLE
            database: pgsql
          - php: 8.3
            moodle-branch: MOODLE_404_STABLE
            database: pgsql

          - php: 8.2
            moodle-branch: MOODLE_403_STABLE
            database: pgsql
          - php: 8.2
            moodle-branch: MOODLE_402_STABLE
            database: pgsql

          - php: 8.1
            moodle-branch: MOODLE_401_STABLE
            database: pgsql

          - php: 8.0
            moodle-branch: MOODLE_400_STABLE
            database: pgsql
            # The following line is only needed if you're going to run php8 jobs and your
            # plugin needs xmlrpc services.
            extensions: xmlrpc-beta
          - php: 8.0
            moodle-branch: MOODLE_311_STABLE
            database: pgsql
            # The following line is only needed if you're going to run php8 jobs and your
            # plugin needs xmlrpc services.
            extensions: xmlrpc-beta

          - php: 7.4
            moodle-branch: MOODLE_310_STABLE
            database: pgsql
          - php: 7.4
            moodle-branch: MOODLE_39_STABLE
            database: pgsql
          - php: 7.4
            moodle-branch: MOODLE_38_STABLE
            database: pgsql

          # Lowest php versions supported by each branch (with main always being tested twice).
          - php: 8.2
            moodle-branch: main
            database: pgsql
          - php: 8.2
            moodle-branch: main
            database: mariadb
          - php: 8.2
            moodle-branch: MOODLE_500_STABLE
            database: pgsql

          - php: 8.1
            moodle-branch: MOODLE_405_STABLE
            database: pgsql
          - php: 8.1
            moodle-branch: MOODLE_404_STABLE
            database: pgsql

          - php: 8.0
            moodle-branch: MOODLE_403_STABLE
            database: pgsql
          - php: 8.0
            moodle-branch: MOODLE_402_STABLE
            database: pgsql

          - php: 7.4
            moodle-branch: MOODLE_401_STABLE
            database: pgsql
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          if [ ${{ matrix.plugin-ci }} ]; then
              composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ${{ matrix.plugin-ci }}
          else
              composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          fi
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
          IGNORE_PATHS: tests/fixtures

      - name: PHP Lint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phplint

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci codechecker --max-warnings 0

      - name: Validating
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci mustache

      - name: Grunt
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci grunt --max-lint-warnings 0

      - name: PHPUnit tests
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpunit

      - name: Behat features
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci behat --profile chrome

      - name: Mark cancelled jobs as failed.
        if: ${{ cancelled() }}
        run: exit 1
